import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/scan_record.dart';
import '../services/scan_store.dart';

/// Builds the Product Inspection Summary Report PDF from all saved records.
///
/// The app runs two independent checks, so the document has two sections —
/// **Label Checks** and **Physical Damage Checks** — each with its own stats
/// and table. A record appears in exactly one of them, per its [ScanType].
class ReportBuilder {
  // ── Colour palette matching the app's soft-green theme ──────────────────
  static const _green = PdfColor.fromInt(0xFF2E7D32);
  static const _greenLight = PdfColor.fromInt(0xFF4CAF50);
  static const _greenBg = PdfColor.fromInt(0xFFE8F5E9);
  static const _blue = PdfColor.fromInt(0xFF1565C0);
  static const _blueBg = PdfColor.fromInt(0xFFE3F2FD);
  static const _amber = PdfColor.fromInt(0xFFE65100);
  static const _amberBg = PdfColor.fromInt(0xFFFFF8E1);
  static const _red = PdfColor.fromInt(0xFFB71C1C);
  static const _redBg = PdfColor.fromInt(0xFFFFEBEE);
  static const _border = PdfColor.fromInt(0xFFC8E0CE);
  static const _muted = PdfColor.fromInt(0xFF6A8F6E);
  static const _text = PdfColor.fromInt(0xFF1A2E1C);
  static const _bg = PdfColor.fromInt(0xFFF0F7F2);
  static const _warningBg = PdfColor.fromInt(0xFFFFF8E1);
  static const _warningText = PdfColor.fromInt(0xFF5C4A1E);

  /// Loads all record folders and their data.json files and builds the PDF.
  static Future<pw.Document> build() async {
    final dir = await ScanStore.rootDir();
    final dirs = _loadAllRecordDirs(dir);
    final records = _parseRecords(dirs);
    return _buildDocument(records);
  }

  // ── Record loading ───────────────────────────────────────────────────────

  static List<Directory> _loadAllRecordDirs(Directory dir) {
    if (!dir.existsSync()) return [];
    return dir.listSync().whereType<Directory>().toList()
      ..sort((a, b) =>
          b.statSync().modified.compareTo(a.statSync().modified));
  }

  /// Folders without a readable data.json are skipped — there's nothing to
  /// report for them and they'd otherwise pad the totals with blank rows.
  static List<_Entry> _parseRecords(List<Directory> dirs) {
    final entries = <_Entry>[];
    for (final d in dirs) {
      final record = ScanStore.load(d);
      if (record == null) continue;
      entries.add(_Entry(name: p.basename(d.path), record: record));
    }
    return entries;
  }

  // ── PDF construction ──────────────────────────────────────────────────────

  static pw.Document _buildDocument(List<_Entry> entries) {
    final doc = pw.Document();

    final labels = entries.where((e) => e.record.isLabelCheck).toList();
    final damages = entries.where((e) => e.record.isDamageCheck).toList();

    // Date range across everything.
    final dates = entries.map((e) => e.record.scannedAt).toList()..sort();
    final earliest = dates.isNotEmpty ? _fmtDate(dates.first) : '—';
    final latest = dates.isNotEmpty ? _fmtDate(dates.last) : '—';
    final generated = _fmtDatetime(DateTime.now());

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        build: (ctx) => [
          _header(generated, earliest, latest),
          pw.SizedBox(height: 16),
          _disclaimer(),
          pw.SizedBox(height: 22),
          ..._labelSection(labels),
          pw.SizedBox(height: 26),
          ..._damageSection(damages),
          pw.SizedBox(height: 24),
          _hotlineFooter(),
        ],
        footer: (ctx) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Generated by Label Check',
                style: pw.TextStyle(fontSize: 9, color: _muted)),
            pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}',
                style: pw.TextStyle(fontSize: 9, color: _muted)),
          ],
        ),
      ),
    );

    return doc;
  }

  // ── Section 1: label checks ───────────────────────────────────────────────

  static List<pw.Widget> _labelSection(List<_Entry> entries) {
    final compliant = entries
        .where((e) => e.record.status == ComplianceStatus.compliant)
        .length;
    final nonCompliant = entries
        .where((e) => e.record.status == ComplianceStatus.nonCompliant)
        .length;
    final banned = entries
        .where((e) => e.record.status == ComplianceStatus.banned)
        .length;

    final flagged = entries
        .where((e) => e.record.status != ComplianceStatus.compliant)
        .toList();

    // Flag-trigger frequency, label checks only.
    final triggerFreq = <String, int>{};
    for (final e in flagged) {
      final k = e.record.matchedKeyword;
      if (k != '—' && k.isNotEmpty) triggerFreq[k] = (triggerFreq[k] ?? 0) + 1;
    }
    final sortedTriggers = triggerFreq.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    return [
      _sectionTitle('1.  Label Checks', _green),
      pw.SizedBox(height: 8),
      pw.Row(children: [
        _statBox('Label Checks', '${entries.length}', _text, _bg),
        pw.SizedBox(width: 8),
        _statBox('Compliant', '$compliant', _green, _greenBg),
        pw.SizedBox(width: 8),
        _statBox('Non-Compliant', '$nonCompliant', _amber, _amberBg),
        pw.SizedBox(width: 8),
        _statBox('Banned', '$banned', _red, _redBg),
      ]),
      pw.SizedBox(height: 14),
      if (entries.isEmpty)
        _emptyNote('No label checks recorded.')
      else ...[
        _subTitle('All label checks'),
        pw.SizedBox(height: 6),
        _labelTable(entries),
        pw.SizedBox(height: 14),
        _subTitle('Common flag triggers'),
        pw.SizedBox(height: 6),
        if (sortedTriggers.isEmpty)
          _emptyNote('No flagged label checks.')
        else
          _triggerTable(sortedTriggers, flagged.length),
      ],
    ];
  }

  static pw.Widget _labelTable(List<_Entry> entries) {
    return pw.Table(
      border: pw.TableBorder.all(color: _border, width: 0.5),
      columnWidths: {
        0: const pw.FlexColumnWidth(2.2),
        1: const pw.FlexColumnWidth(2.4),
        2: const pw.FlexColumnWidth(1.6),
        3: const pw.FlexColumnWidth(1.4),
        4: const pw.FlexColumnWidth(1.8),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _greenBg),
          children: [
            _tableCell('Record', header: true),
            _tableCell('Product Name', header: true),
            _tableCell('Expiration Date', header: true),
            _tableCell('All Labels Present', header: true),
            _tableCell('Status', header: true),
          ],
        ),
        ...entries.map((e) {
          final r = e.record;
          final statusColor = switch (r.status) {
            ComplianceStatus.compliant => _green,
            ComplianceStatus.nonCompliant => _amber,
            ComplianceStatus.banned => _red,
          };
          return pw.TableRow(children: [
            _tableCell(e.name),
            _tableCell(r.productName),
            _tableCell(r.expiration),
            _tableCell(r.allLabelsPresent ? 'Yes' : 'No'),
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                r.status == ComplianceStatus.banned
                    ? 'BANNED'
                    : r.statusLabel,
                style: pw.TextStyle(
                    fontSize: 8.5,
                    fontWeight: pw.FontWeight.bold,
                    color: statusColor),
              ),
            ),
          ]);
        }),
      ],
    );
  }

  static pw.Widget _triggerTable(
      List<MapEntry<String, int>> triggers, int totalFlagged) {
    return pw.Table(
      border: pw.TableBorder.all(color: _border, width: 0.5),
      columnWidths: {
        0: const pw.FlexColumnWidth(3),
        1: const pw.FlexColumnWidth(1.5),
        2: const pw.FlexColumnWidth(1.5),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _greenBg),
          children: [
            _tableCell('Keyword / Reason', header: true),
            _tableCell('Occurrences', header: true),
            _tableCell('% of Flagged', header: true),
          ],
        ),
        ...triggers.map((e) {
          final pct = totalFlagged > 0
              ? '${(e.value / totalFlagged * 100).toStringAsFixed(0)}%'
              : '—';
          return pw.TableRow(children: [
            _tableCell(e.key),
            _tableCell('${e.value}'),
            _tableCell(pct),
          ]);
        }),
      ],
    );
  }

  // ── Section 2: physical damage checks ─────────────────────────────────────

  static List<pw.Widget> _damageSection(List<_Entry> entries) {
    final damaged =
        entries.where((e) => e.record.damageCheck.isDamaged).length;
    final clean = entries
        .where((e) =>
            e.record.damageCheck.available && !e.record.damageCheck.isDamaged)
        .length;
    final unavailable =
        entries.where((e) => !e.record.damageCheck.available).length;

    return [
      _sectionTitle('2.  Physical Damage Checks', _blue),
      pw.SizedBox(height: 8),
      pw.Row(children: [
        _statBox('Damage Checks', '${entries.length}', _text, _bg),
        pw.SizedBox(width: 8),
        _statBox('No Damage', '$clean', _green, _greenBg),
        pw.SizedBox(width: 8),
        _statBox('Damaged', '$damaged', _red, _redBg),
        pw.SizedBox(width: 8),
        _statBox('Not Checked', '$unavailable', _muted, _bg),
      ]),
      pw.SizedBox(height: 14),
      if (entries.isEmpty)
        _emptyNote('No physical damage checks recorded.')
      else ...[
        _subTitle('All damage checks'),
        pw.SizedBox(height: 6),
        _damageTable(entries),
        pw.SizedBox(height: 10),
        _modelNote(),
      ],
    ];
  }

  static pw.Widget _damageTable(List<_Entry> entries) {
    return pw.Table(
      border: pw.TableBorder.all(color: _border, width: 0.5),
      columnWidths: {
        0: const pw.FlexColumnWidth(2.2),
        1: const pw.FlexColumnWidth(1.5),
        2: const pw.FlexColumnWidth(1.4),
        3: const pw.FlexColumnWidth(1.6),
        4: const pw.FlexColumnWidth(2.0),
        5: const pw.FlexColumnWidth(1.3),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _blueBg),
          children: [
            _tableCell('Record', header: true),
            _tableCell('Date', header: true),
            _tableCell('Damaged', header: true),
            _tableCell('Damage Type', header: true),
            _tableCell('Sides Affected', header: true),
            _tableCell('Confidence', header: true),
          ],
        ),
        ...entries.map((e) {
          final d = e.record.damageCheck;
          if (!d.available) {
            return pw.TableRow(children: [
              _tableCell(e.name),
              _tableCell(_fmtDate(e.record.scannedAt)),
              _tableCell('Not checked'),
              _tableCell('—'),
              _tableCell('—'),
              _tableCell('—'),
            ]);
          }
          return pw.TableRow(children: [
            _tableCell(e.name),
            _tableCell(_fmtDate(e.record.scannedAt)),
            pw.Padding(
              padding: const pw.EdgeInsets.all(6),
              child: pw.Text(
                d.isDamaged ? 'YES' : 'NO',
                style: pw.TextStyle(
                    fontSize: 8.5,
                    fontWeight: pw.FontWeight.bold,
                    color: d.isDamaged ? _red : _green),
              ),
            ),
            _tableCell(d.isDamaged ? d.damageTypes.join(', ') : '—'),
            _tableCell(d.isDamaged
                ? '${d.affectedSides} (${d.totalSpots} spot(s))'
                : '—'),
            _tableCell(d.isDamaged
                ? '${(d.maxConfidence * 100).toStringAsFixed(0)}%'
                : '—'),
          ]);
        }),
      ],
    );
  }

  /// Spells out the single-class limitation so a reader doesn't take the
  /// uniform "Damage" type column as a modelling result.
  static pw.Widget _modelNote() {
    return pw.Container(
      padding: const pw.EdgeInsets.all(9),
      decoration: pw.BoxDecoration(
        color: _blueBg,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
        border: pw.Border.all(color: _border),
      ),
      child: pw.Text(
        'Damage detection uses an on-device YOLO11n model trained on a '
        'single damage class, so it reports that packaging damage is present, '
        'where on the box it was found, and with what confidence — but not '
        'which kind of damage it is. The Damage Type column will differentiate '
        'dents, tears and similar only once the model is retrained with '
        'per-type classes.',
        style: pw.TextStyle(fontSize: 8.5, color: _blue),
      ),
    );
  }

  // ── Shared section builders ───────────────────────────────────────────────

  static pw.Widget _header(String generated, String earliest, String latest) {
    return pw.Container(
      width: double.infinity,
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Label Check',
            style: pw.TextStyle(
              fontSize: 28,
              fontWeight: pw.FontWeight.bold,
              color: _green,
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Product Inspection Summary Report',
            style: pw.TextStyle(
                fontSize: 16, fontWeight: pw.FontWeight.bold, color: _text),
          ),
          pw.SizedBox(height: 6),
          pw.Divider(color: _greenLight, thickness: 1.5),
          pw.SizedBox(height: 4),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Generated: $generated',
                  style: pw.TextStyle(fontSize: 9, color: _muted)),
              pw.Text('Period: $earliest – $latest',
                  style: pw.TextStyle(fontSize: 9, color: _muted)),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _disclaimer() {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: _warningBg,
        border: pw.Border.all(color: const PdfColor.fromInt(0xFFFFE082)),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Text(
        'This report is generated by Label Check from two independent automated '
        'inspections: label compliance (OCR + matching against FDA Philippines '
        'advisories) and physical packaging damage (on-device object detection). '
        'It is for informational purposes only and does not constitute an '
        'official FDA determination. To report a product, contact the FDA '
        'Philippines hotline listed at the end of this report.',
        style: pw.TextStyle(fontSize: 8.5, color: _warningText),
      ),
    );
  }

  static pw.Widget _sectionTitle(String title, PdfColor color) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(title,
            style: pw.TextStyle(
                fontSize: 15, fontWeight: pw.FontWeight.bold, color: color)),
        pw.SizedBox(height: 3),
        pw.Divider(color: color, thickness: 1.2),
      ],
    );
  }

  static pw.Widget _subTitle(String title) {
    return pw.Text(title,
        style: pw.TextStyle(
            fontSize: 11, fontWeight: pw.FontWeight.bold, color: _text));
  }

  static pw.Widget _statBox(
      String label, String value, PdfColor textColor, PdfColor bgColor) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.symmetric(vertical: 14, horizontal: 10),
        decoration: pw.BoxDecoration(
          color: bgColor,
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
          border: pw.Border.all(color: _border),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            pw.Text(value,
                style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                    color: textColor)),
            pw.SizedBox(height: 4),
            pw.Text(label,
                style: pw.TextStyle(fontSize: 8.5, color: _muted),
                textAlign: pw.TextAlign.center),
          ],
        ),
      ),
    );
  }

  static pw.Widget _hotlineFooter() {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: _greenBg,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
        border: pw.Border.all(color: _border),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('FDA Philippines',
              style: pw.TextStyle(
                  fontSize: 10,
                  fontWeight: pw.FontWeight.bold,
                  color: _green)),
          pw.SizedBox(height: 4),
          pw.Text(
            'Hotline: (02) 8807-0751  ·  Email: fdaphils@fda.gov.ph  ·  Site: www.fda.gov.ph\n'
            'If any product above is suspected to be dangerous or unregistered, please report it through the official FDA channel.',
            style: pw.TextStyle(fontSize: 8.5, color: _green),
          ),
        ],
      ),
    );
  }

  static pw.Widget _tableCell(String text, {bool header = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: header ? pw.FontWeight.bold : pw.FontWeight.normal,
          color: _text,
        ),
      ),
    );
  }

  static pw.Widget _emptyNote(String msg) {
    return pw.Text(msg, style: pw.TextStyle(fontSize: 9, color: _muted));
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  static String _fmtDate(DateTime dt) =>
      '${dt.year}-${_pad(dt.month)}-${_pad(dt.day)}';

  static String _fmtDatetime(DateTime dt) =>
      '${_fmtDate(dt)}  ${_pad(dt.hour)}:${_pad(dt.minute)}';

  static String _pad(int n) => n.toString().padLeft(2, '0');
}

// ── Internal model ────────────────────────────────────────────────────────────

/// One saved record plus the folder name it was saved under.
class _Entry {
  final String name;
  final ScanRecord record;

  const _Entry({required this.name, required this.record});
}
